server:
  port: 8001
###服务别名---服务注册到注册中心的名称
spring:
  application:
    name: mzd-order
eureka:
  instance:
    ##客户端自己告诉服务端多少秒发送一个心跳包
    lease-renewal-interval-in-seconds: 1
    ##客户端告诉服务端等待多少秒之后如果还是没有收到心跳包，那就把我剔除吧
    #lease-expiration-duration-in-seconds: 2
version: test01
